site_name: MapManager
site_description: Dendritic Spine Analysis
site_author: Robert H Cudmore (plust others)

repo_name: MapManager-Docs
repo_url: https://github.com/mapmanager/MapManager-Docs
edit_uri: ""

theme:
    name: material
    custom_dir: 'theme'
    features:
        - navigation.instant
        #- navigation.expand

extra_css:
  - css/style.css

watch:
  - .

markdown_extensions:
  - pymdownx.superfences
  # to allow tabs in markdown
  - pymdownx.tabbed:
      alternate_style: true
  #
  - admonition
  - pymdownx.details
  # allow links to open in a new tab, use [MapManagerCore Documentation](https://mapmanager.net/MapManagerCore/){target="_blank"}
  - attr_list
  # allows emojis, we will use this for icons to show links open in new tab
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false  # default false
            show_root_toc_entry: true  # default true
            show_category_heading: true
            group_by_category: true  # default true
            heading_level: 2  # default 2
            #show_object_full_path: true
            show_submodules: false
            show_source: true
            # docstring_style: numpy
            docstring_style: google
            docstring_section_style: table  # table, list, spacey
            show_signature_annotations: true  # true is a little to verbose, false is not verbose enough
            # show_root_heading: true

nav:
    - Getting Started: getting-started.md
    - Supported File Formats: supported-file-formats.md
    - API:
        - MapManager Core: mapmanagercore.md
