site_name: MapManager Documentation
site_description: Dendritic Spine Analysis
site_author: Robert H Cudmore (plust others)

repo_name: MapManager-Dev
repo_url: https://github.com/mapmanager/MapManager-Dev
edit_uri: ""

theme:
    name: material
    custom_dir: 'theme'
    features:
        - navigation.instant
        #- navigation.expand

extra_css:
  - css/style.css

watch:
  - .

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false  # default false
            show_root_toc_entry: true  # default true
            show_category_heading: true
            group_by_category: true  # default true
            heading_level: 2  # default 2
            #show_object_full_path: true
            show_submodules: false
            show_source: true
            # docstring_style: numpy
            docstring_style: google
            docstring_section_style: table  # table, list, spacey
            show_signature_annotations: true  # true is a little to verbose, false is not verbose enough
            # show_root_heading: true

nav:
    - Getting Started: getting_started.md
    - Interface: interface.md
    - Supported File Formats: supported-file-formats.md
    - API:
        - MapManager Core: mapmanagercore.md
